{{- if .Values.postfix.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "postfix.fullname" . }}
  labels:
    {{- include "postfix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postfix.service.type }}
  ports:
    - port: {{ .Values.postfix.service.port }}
      targetPort: 25
      protocol: TCP
      name: smtp
  selector:
    {{- include "postfix.selectorLabels" . | nindent 4 }}
{{- end }}
