# Default values for infrastructure-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Configuration for managing dependencies - this chart now acts as a meta-application
# that references sealed-secrets and postfix applications through ArgoCD

# Sealed Secrets configuration (dependency management)
sealedSecrets:
  enabled: true

# Postfix server configuration (dependency management)  
postfix:
  enabled: true

# Simplified values for the meta-application - removing service-specific configurations 
# since this chart no longer deploys services directly
replicaCount: 1

# Basic configuration that may be needed for ArgoCD integration or future expansion
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

# Service account and security context - minimal needed for meta-application function
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

# Minimal ingress configuration (can be removed or expanded as needed)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# HTTPRoute configuration  
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
  - name: gateway
    sectionName: http
  hostnames:
  - chart-example.local
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers

# Resources and probes - minimal configuration for meta-application 
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Autoscaling - can be enabled later if needed
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Volume configurations (minimal)
volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
