apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-parallel
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    targetRevision: HEAD
    path: traefik-parallel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
