apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postfix
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/smoki99/homelab-chart.git
    targetRevision: HEAD
    path: postfix
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
