apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portainer-agent.fullname" . }}
  labels:
    {{- include "portainer-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.agent.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "portainer-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "portainer-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "portainer-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: agent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          ports:
            - containerPort: 9001
              name: agent
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              valueFrom:
                {{- if eq .name "KUBERNETES_POD_IP" }}
                fieldRef:
                  fieldPath: status.podIP
                {{- else if eq .name "AGENT_PORT" }}
                # Value is hardcoded for AGENT_PORT
                {{- end }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: agent
          readinessProbe:
            httpGet:
              path: /
              port: agent
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
