# Headless service for agent communication
apiVersion: v1
kind: Service
metadata:
  name: {{ include "portainer-agent.fullname" . }}-headless
  labels:
    {{- include "portainer-agent.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: tunnel
  selector:
    {{- include "portainer-agent.selectorLabels" . | nindent 4 }}
