apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/smoki99/homelab-chart.git
    targetRevision: HEAD
    path: portainer-agent
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
