# Values for Portainer Agent deployment
# This file contains configuration specific to the agent-only deployment

# Portainer Agent specific settings
agent:
  # Enable/disable the agent component  
  enabled: true
  
  # Image configuration
  image:
    repository: portainer/agent
    tag: "2.19.2"
    pullPolicy: IfNotPresent
    
  # Service configuration for agent access  
  service:
    type: ClusterIP
    port: 9001
    
  # Deployment settings
  deployment:
    replicas: 1
    
  # Resource limits (minimal for agent)
  resources: {}
  
  # Node selector and tolerations
  nodeSelector: {}
  tolerations: []
  
  # Security context
  securityContext: {}
  podSecurityContext: {}

# Environment variables needed by Portainer Agent
env:
  # Required for Kubernetes deployment
  - name: KUBERNETES_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: AGENT_PORT  
    value: "9001"

# Disable persistence since this is just an agent component
persistence:
  enabled: false

# Ingress configuration (disabled by default)
ingress:
  enabled: false
