# Default values for portainer-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Portainer Agent configuration
agent:
  # Enable/disable the agent deployment
  enabled: true

# Service configuration  
service:
  type: ClusterIP
  port: 9001

# Deployment configuration  
deployment:
  replicas: 1
  image:
    repository: portainer/agent
    tag: "2.19.2"
    pullPolicy: IfNotPresent

# Resource limits and requests
resources: {}
#  limits:
#    cpu: 500m
#    memory: 512Mi
#  requests:
#    cpu: 100m
#    memory: 256Mi

# Node selector for deployment
nodeSelector: {}

# Tolerations for scheduling
tolerations: []

# Affinity rules
affinity: {}

# Security context
securityContext: {}
podSecurityContext: {}

# Service account configuration
serviceAccount:
  create: true
  name: ""
  automount: true

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Ingress configuration (disabled by default)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Environment variables
env: {}

# Volume configurations
volumes: []
volumeMounts: []
