{{- if .Values.postfix.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "infrastructure-base.fullname" . }}-postfix
  labels:
    {{- include "infrastructure-base.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postfix.service.type }}
  ports:
    - port: {{ .Values.postfix.service.port }}
      targetPort: 25
      protocol: TCP
      name: smtp
  selector:
    {{- include "infrastructure-base.selectorLabels" . | nindent 4 }}
{{- end }}
