apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: traefik
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  # Ensure the namespace exists by setting the destination to create it if needed  
  # In a real deployment, ensure infrastructure namespace is already created
  # Added proper validation fields for ArgoCD applications
  ignoreDifferences:
  - group: ""
    kind: Namespace
    jsonPointers:
    - /status
